In [2]:
print("Hello, Jupyter in VS Code!")

Hello, Jupyter in VS Code!


In [20]:
import numpy as np 
array_1D=[1,2,3]
print("The 1D array value are:",array_1D)
array_2D= ([[1,2,3],[5,6,7]])
print("The 2D array is:",array_2D)

The 1D array value are: [1, 2, 3]
The 2D array is: [[1, 2, 3], [5, 6, 7]]


In [ ]:
# List vs numpy array 
import numpy as np 
import time
py_list = [1,2,3]
print("The python value are ",py_list*2)
py_array = np.array([1,2,3])
print("The value are ",py_array);
start = time.time ()
py_list = [i*2 for i in range (10000)]
print(py_list)
print("\n List operation time: ",time.time()-start)

start = time.time()
py_array = np.arange(100000)*2
print("\n List operation time: ",time.time()-start)







In [42]:
# Creating array from scractch 
zeros = np.zeros ((3,4))  #  Here we have 3 row with the 4 column .
print(zeros)
first = np.ones ((2,3))
print("The valuse of the one is \n",first)
cringe= np.random.random((2,3))
print("The randp values are  \n",cringe)
meow = np.full ((3,5),7)
print("The value are",meow)
sequence = np.arange (0,20,2)  # It will skip the last number 
print(sequence)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The valuse of the one is 
 [[1. 1. 1.]
 [1. 1. 1.]]
The randp values are  
 [[0.1835266  0.73430649 0.22220025]
 [0.36320169 0.50657818 0.37615492]]
The value are [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[ 0  2  4  6  8 10 12 14 16 18]


In [51]:
# Vector and Matrices and the tensor 
Vector = np.array([1,2,3])
print ('Vector',Vector)
Matrix = np.array([[1,2,3],[2,3,4]])
print (Matrix)
Tensor = np.array ([[[1,2] , [3,4]],[[5,6],[7,8]]])  # This is 3D tensor 
print("The tensor are \n",Tensor.ndim)

Vector [1 2 3]
[[1 2 3]
 [2 3 4]]
The tensor are 
 3


In [54]:
# Arrays properties 
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print("Shape",array.shape)
print("Dimensions",array.ndim)
print("DatatYPE",array.dtype)
print ("Size",array.size)

Shape (2, 3)
Dimensions 2
DatatYPE int64
Size 6


In [64]:
# Arrays reshaping 
arr = np.arange(12)
print("Orignal array is ",arr)
reshaped = arr.reshape ((3,4))
print ("The reshaped value are \n",reshaped)
flatterned = arr.flatten()
print ("The value is flatterned",flatterned)
raveled = arr.ravel()
print ("The value are ",raveled);
transpose = reshaped.T  # This calculation is complex 
print ("The transpose value are", transpose)

Orignal array is  [ 0  1  2  3  4  5  6  7  8  9 10 11]
The reshaped value are 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The value is flatterned [ 0  1  2  3  4  5  6  7  8  9 10 11]
The value are  [ 0  1  2  3  4  5  6  7  8  9 10 11]
The transpose value are [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# Slicing 
